sequenceDiagram
    title: Create Portfolio
    actor User as Samantha
    participant DappUI as Orchy
    participant sw as SmartWallet
    participant Contract as stake.contract
    participant SMK as Portfolio
    participant OsmosisWallet as Osmosis ICA

    User ->> DappUI: check osmosis,<br/>dialy, stake on receipt, restake
    User ->> DappUI: Create Portfolio
    DappUI -->> sw: makeStakeManagementInvitation({ osmosis:<br/> { freq: 'daily', onReceipt: ['stake'], onRewards: ['restake'] })
    sw -->> Contract: makeStakeManagementInvitation(...)<br/> { give: { Fee, Retainer } }
    Contract -->> SMK: create StakeManagementKit({freq: 'daily', ...})
    SMK -->> OsmosisWallet: osmosis.makeAccount()
    Contract -->> sw: invitationMakers
    sw -->> DappUI: payouts: 0
