name: Deploy StkC

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  integration:
    runs-on: ubuntu-latest
    env:
      HOME: /home/runner/work

    steps:
      - name: Checkout this repo
        uses: actions/checkout@v4

      - name: Use Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: yarn install

      - name: Start Agoric Local Chain
        run: yarn start:chain

      - name: Wait for Agoric Local Chain to be ready
        run: yarn wait-for-agd-block

      - name: Deploy Staking contract
        run: yarn deploy:contract

      - name: test
        run: sleep 120 && docker logs agoric

      - name: Verify Staking contract installation from vStorage
        run: ./scripts/check-vstorage.mjs
        env:
          vStorageUrl: http://localhost:1317/agoric/vstorage/data/published.agoricNames.instance
          valueToFind: StkC
