name: PR

on:
  pull_request:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout this repo
        uses: actions/checkout@v4

      - name: Use Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install root dependencies
        run: yarn install

      - name: Run tests
        run: yarn test

      - name: Run lint check
        run: yarn lint

      - name: Build UI
        run: cd ui && yarn build
